Revert "removed redundant grad compute"
This reverts commit b6b93ff129e67202391f7b4a939d2797ed0d37cf.

- Removing the first declaration of `grad` causes this because `grad` is checked inside the while loop
UndefVarError: `grad` not defined

- A semicolon is used in the rmsprop, sgd_momentum, and adam functions so the hyperparameters can be referenced as keyword arguments